# Usa la imagen oficial de Consul
FROM hashicorp/consul

# Exponer puertos para la interfaz web de Consul y para el clúster
EXPOSE 8500 8301 8301/udp 8302 8302/udp 8300 8600 8600/udp

# Configura el punto de entrada con opciones para ejecutar Consul
ENTRYPOINT ["consul", "agent", "-dev", "-client", "0.0.0.0"]